name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true # Checkout private submodules(themes or something else).
    - uses: actions/checkout@v3
      with:
        repository: leoleoasd/blog
        path: .deploy_git
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      id: cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install --frozen-lockfile --dev
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      run: |
        mkdir /home/runner/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        git config --global user.email "blog_deployer@yuxuan.lu"
        git config --global user.name "Yuxuan Lu"
        # Initialize target with currently deployed files
        cd .deploy_git
        ls
        # Remove all files before they get copied from ../public/
        # so git can track files that were removed in the last commit
        find . -path ./.git -prune -o -exec rm -rf {} \;
        cd ../
        ./node_modules/.bin/hexo g -d -m "${{ github.event.head_commit.message }}"
